name: sufismart
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
 
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  font_awesome_flutter: ^9.2.0
  http: ^0.13.4
  dio: ^4.0.4
  card_swiper: ^1.0.4
  fancy_bottom_navigation: ^0.3.3
  cached_network_image: ^3.2.0
  skeleton_text: ^3.0.0
  onesignal_flutter: ^3.2.8
  permission_handler: ^8.3.0
  uni_links: ^0.5.1
  url_launcher: ^6.0.18
  flutter_launcher_icons: ^0.9.0
  shared_preferences: ^2.0.12
  sqflite: ^2.0.2
  intl: ^0.17.0
  image_picker: ^0.8.2
  flutter_image_compress: ^1.1.0
  flutter_background_service: ^1.0.4
  flutter_background_service_android: ^1.0.2
  flutter_background_service_ios: ^1.0.2
  geolocator: ^8.2.0
  google_maps_flutter: ^2.1.3
  sprintf: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^1.0.0 
  
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - dbmigration/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
